# CRMEB 相关配置
crmeb:
  version: CRMEB-JAVACORE-MER-DFYHZ-v1.4_beta # 当前代码版本为企业版本 授权给巅峰云（杭州）网络科技有限公司
  domain: #配合swagger使用 # 待部署域名
  wechat-api-url:  #请求微信接口中专服务器
  asyncConfig: false #是否同步config表数据到redis
  imagePath: /Users/stivepeim/Documents/ZBKJ/CODEMANGER/BIZ-CODE/JavaMer/V1.4/ # 服务器图片路径配置 斜杠结尾
  retailStoreBrokerageRatio: 30 #佣金返佣比例和上限
  activityStyleCachedTime: 10 #活动边框缓存周期 秒为单位，生产环境适当5-10分钟即可
  activityStyleProductLimit: 300 # 活动边框指定商品上线
  productTagCacheMinutes: 10 # 商品标签缓存分钟数
  orderCancelTime: 30 # 订单支付取消时间，单位分钟
  ignored: #安全路径白名单
    - swagger-ui/
    - swagger-resources/**
    - /**/v2/api-docs
    - /**/*.html
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.map
    - /favicon.ico
    - /actuator/**
    - /druid/**
    - api/front/pagediy/info
    - /**/getPlatformUserInfo
    - /jushuitan/**
    - /**/visa/userVisaCallback
    - /**/tankOrder/callapi
    - /**/cbec_order/sync
# 配置端口
server:
#  port: 8182
  port: 8080
  servlet:
    context-path: /         # 访问path
  tomcat:
    uri-encoding: UTF-8     # 默认编码格式
    max-threads: 1000       # 最大线程数量 默认200
    min-spare-threads: 30   # 初始化启动线程数量

spring:
  profiles:
    active: sm-front
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${crmeb.filePath}
    add-mappings: true
  application:
    name: crmeb-front #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://wkp2.cqrfkonij3bk.ap-southeast-1.rds.amazonaws.com:3306/sm?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8&allowMultiQueries=true
    username: root
    password: smbs8888#
  redis:
    host: 127.0.0.1 #地址
    port: 6379 #端口
    password:
    timeout: 30000 # 连接超时时间（毫秒）
    database: 13  #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  # 捕获404异常
  mvc:
    throw-exception-if-no-handler-found: true

debug: true
logging:
  level:
    io.swagger.*: error
    com.zbjk.crmeb: debug
    org.springframework.boot.autoconfigure: ERROR
  config: classpath:logback-spring.xml
  file:
    path: ./crmeb_log

# mybatis 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  # 配置slq打印日志
  configuration:
    cache-enabled: false #禁用二级缓存
    local-cache-scope: statement #一级缓存指定为statement级别
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
#      logic-delete-field: isDel  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 行为验证码
aj:
  captcha:
    type: default       # 验证码类型
    water-mark: Jbp Java   # 水印
    slip-offset: 5      # 校验滑动拼图允许误差偏移量(默认5像素)
    aes-status: true    # aes加密坐标开启或者禁用(true|false)
    interference-options: 2 # 滑动干扰项(0/1/2)
    font-style: 1       # 点选字体样式 默认Font.BOLD
    font-size: 25       # 点选字体字体大小
    req-frequency-limit-enable: false   # 接口请求次数一分钟限制是否开启 true|false
    req-get-lock-limit: 5     # 验证失败5次，get接口锁定
    req-get-minute-limit: 360     # 验证失败后，锁定时间间隔,s
    req-check-minute-limit: 60    # check接口一分钟内请求数限制
    req-verify-minute-limit: 60     # verify接口一分钟内请求数限制

#swagger 配置
swagger:
  basic:
    enable: true #是否开启
    check: false #是否打开验证
    username: root
    password: 12345Aa#

# wx-java-tools 第三方框架仅仅用到了微信小程序直播功能 是用小程序直播时必须配置
wx:
  miniapp:
    configs:
      - appid: wxfcc6dbbeb00cb7a3 #微信小程序的appid
        secret: b74d9d5fe953f32f4a8461246dbdc2eb #微信小程序的Secret
        token: CrmebJava #微信小程序消息服务器配置的token
        aesKey: 111 #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
    config-storage:
      type: redistemplate
rsa:
  encrypt:
    open: true # 是否开启加密 true  or  false
    showLog: true # 是否打印加解密log true  or  false
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo8jKuU2/N4zvyDVdvlLwUoPTW672DtbGV7Tvek1dlmaaxV4IiA2ZNIfpXfzD3ERzN9/MQii80YkmOkpDlAAPIAOHikMhhfbMqsy13tL/z9pQO5Icu6X2VfdHUdKDEOUTnD/lA0tRwu80dw/+VOkvzg7I3qDcT6gsRs9J92SN+KydMeulqk/AjZomP9/ISgz2i8gLi62jCswbCsvqg9kx7FMq4p/fHTqCXvDPt6ebEQbFh0FP2TmD/f7XISUeplD45u19yheYfPt1UvjePKZrbuHWTmB7YfNSdBv9rCREllxc/nQ6o4LB2alW7ZoGWc3PjlH1MwpTe0Q3Iopi6nT20QIDAQAB

kq:
  config: jh.properties

historyOrder:
  ifOpenOrder: true
  name: wkp42271043176625
  ifAgent: true

internal:
  uid: 10000001,10000002,10000003,10000004,10000005,10000006,10000007,10000008,10000009,10000010,10000011,10000012,10000013,10000014,10000015

gxc:
  url: https://sm.fnyss.cc

platform:
  appId: wx6eb1c319ea4c845c,wx225294ae84eb02f6,wx73e7a53cd7f554e6
  dbName: sm,tf,yk
  openWaitStatus: 1


jushuitan:
  appKey: 60fe53c33c1b4fbbb243f6990e852132
  appSecret: cad5739f959c4cbc94be68b493d9e194
  url: https://sm.fnyss.cc/api/front/jushuitan/auth/callApi

teamAmtSelf:
  ifopen: true
  filterList: 1000036,1000052,1000075